SEQ_LEN = 30
N_POINTS = 200
CONDITION_FEATURE_DIM = 3 # <<< MUST SET THIS BASED ON THEIR DATA SHAPE (e.g., 3 if X_Y_combined has columns [x1, x2, y])
PAD_TOKEN_ID = 0
VOCAB_SIZE = 19

# Model Capacity
EMBED_DIM = 512
NUM_HEADS = 16
NUM_LAYERS = 16
DIM_FEEDFORWARD = 2048
DROPOUT = 0.1

# Diffusion Parameters
NUM_TIMESTEPS = 500
BETA_START = 0.0001
BETA_END = 0.02
SCHEDULE_TYPE = 'cosine'

# Training Parameters
BATCH_SIZE = 128

EOS_TOKEN_ID = 2 
EOS_LOSS_WEIGHT = 2.0 

VALIDATION_BATCH_SIZE = 2048
LEARNING_RATE = 1e-4
EPOCHS = 500
PATIENCE = 10
BEST_MODEL_PATH = "model_weights.pth"